# git completion
__git_complete g _git
__git_complete gch _git_checkout
__git_complete gco _git_commit
__git_complete gdi _git_diff
__git_complete gst _git_status
__git_complete gbr _git_branch
__git_complete gpull _git_pull
__git_complete gpush _git_push
