#!/usr/bin/env bash

trap ctrl_c INT
function ctrl_c() {
    echo "** Trapped CTRL-C"
    exit 1
}

brew_command=/usr/local/bin/brew
brew_cask_command="$brew_command cask"
failed_items=""
function install_package() {
    echo EXECUTING: brew install $1 $2
    $brew_command install $1 $2
    [ $? -ne 0 ] && $failed_items="$failed_items $1"  # package failed to install.
}
function install_cask_package() {
    echo EXECUTING: brew cask install $1
    $brew_cask_command install $1
    [ $? -ne 0 ] && $failed_items="$failed_items $1"  # package failed to install.
}
/usr/local/bin/brew tap ==> Auto-updated Homebrew!
/usr/local/bin/brew tap Updated 2 taps (caskroom/cask, homebrew/core).
/usr/local/bin/brew tap ==> Updated Formulae
/usr/local/bin/brew tap acpica
/usr/local/bin/brew tap allure
/usr/local/bin/brew tap ansifilter
/usr/local/bin/brew tap arx-libertatis
/usr/local/bin/brew tap ascii
/usr/local/bin/brew tap aspell
/usr/local/bin/brew tap basex
/usr/local/bin/brew tap bash-snippets
/usr/local/bin/brew tap blastem
/usr/local/bin/brew tap certstrap
/usr/local/bin/brew tap cmark
/usr/local/bin/brew tap collector-sidecar
/usr/local/bin/brew tap dbhash
/usr/local/bin/brew tap diff-pdf
/usr/local/bin/brew tap diffoscope
/usr/local/bin/brew tap django-completion
/usr/local/bin/brew tap duck
/usr/local/bin/brew tap elixir
/usr/local/bin/brew tap emscripten
/usr/local/bin/brew tap fizsh
/usr/local/bin/brew tap fontforge
/usr/local/bin/brew tap fonttools
/usr/local/bin/brew tap fs-uae
/usr/local/bin/brew tap fzf
/usr/local/bin/brew tap geoserver
/usr/local/bin/brew tap getdns
/usr/local/bin/brew tap git
/usr/local/bin/brew tap git-flow-avh
/usr/local/bin/brew tap glew
/usr/local/bin/brew tap gofabric8
/usr/local/bin/brew tap gource
/usr/local/bin/brew tap grafana
/usr/local/bin/brew tap idris
/usr/local/bin/brew tap immortal
/usr/local/bin/brew tap jenkins
/usr/local/bin/brew tap lean-cli
/usr/local/bin/brew tap libpng
/usr/local/bin/brew tap libvirt
/usr/local/bin/brew tap logstalgia
/usr/local/bin/brew tap makensis
/usr/local/bin/brew tap mal4s
/usr/local/bin/brew tap micro
/usr/local/bin/brew tap minimal-racket
/usr/local/bin/brew tap monetdb
/usr/local/bin/brew tap mycli
/usr/local/bin/brew tap nmap
/usr/local/bin/brew tap nzbget
/usr/local/bin/brew tap openclonk
/usr/local/bin/brew tap opencsg
/usr/local/bin/brew tap openmsx
/usr/local/bin/brew tap openshift-cli
/usr/local/bin/brew tap orientdb
/usr/local/bin/brew tap passenger
/usr/local/bin/brew tap pdf2htmlex
/usr/local/bin/brew tap pdftoedn
/usr/local/bin/brew tap pdftoipe
/usr/local/bin/brew tap platformio
/usr/local/bin/brew tap poppler
/usr/local/bin/brew tap ppsspp
/usr/local/bin/brew tap pre-commit
/usr/local/bin/brew tap qemu
/usr/local/bin/brew tap re2
/usr/local/bin/brew tap redis@3.2
/usr/local/bin/brew tap rlvm
/usr/local/bin/brew tap rtags
/usr/local/bin/brew tap saltstack
/usr/local/bin/brew tap sane-backends
/usr/local/bin/brew tap sbcl
/usr/local/bin/brew tap sqldiff
/usr/local/bin/brew tap sqlite
/usr/local/bin/brew tap sqlite-analyzer
/usr/local/bin/brew tap supertux
/usr/local/bin/brew tap swiftlint
/usr/local/bin/brew tap terraform
/usr/local/bin/brew tap translate-toolkit
/usr/local/bin/brew tap watchman
/usr/local/bin/brew tap watson
/usr/local/bin/brew tap widelands
/usr/local/bin/brew tap wimlib
/usr/local/bin/brew tap wine
/usr/local/bin/brew tap ==> Renamed Formulae
/usr/local/bin/brew tap transfig -> fig2dev
/usr/local/bin/brew tap 
/usr/local/bin/brew tap carsdotcom/tap
/usr/local/bin/brew tap caskroom/cask
/usr/local/bin/brew tap homebrew/core
/usr/local/bin/brew tap homebrew/dupes
/usr/local/bin/brew tap homebrew/python
/usr/local/bin/brew tap homebrew/versions
/usr/local/bin/brew tap jingweno/gh
/usr/local/bin/brew tap neovim/neovim
install_package apr ''
install_package apr ''
install_package apr-util ''
install_package apr-util ''
install_package archey ''
install_package archey ''
install_package autoconf ''
install_package autoconf ''
install_package automake ''
install_package automake ''
install_package awscli ''
install_package awscli ''
install_package bash ''
install_package bash ''
install_package bash-completion ''
install_package bash-completion ''
install_package bash-git-prompt ''
install_package bash-git-prompt ''
install_package bdw-gc ''
install_package bdw-gc ''
install_package c-ares ''
install_package c-ares ''
install_package cairo ''
install_package cairo ''
install_package casperjs ''
install_package casperjs ''
install_package chromedriver ''
install_package chromedriver ''
install_package cmake ''
install_package cmake ''
install_package coreutils ''
install_package coreutils ''
install_package cscope ''
install_package cscope ''
install_package dialog ''
install_package dialog ''
install_package dos2unix ''
install_package dos2unix ''
install_package expect ''
install_package expect ''
install_package figlet ''
install_package figlet ''
install_package fontconfig ''
install_package fontconfig ''
install_package freetype ''
install_package freetype ''
install_package gd ''
install_package gd ''
install_package gdb ''
install_package gdb ''
install_package gdbm ''
install_package gdbm ''
install_package gettext ''
install_package gettext ''
install_package gh ''
install_package gh ''
install_package ghc ''
install_package ghc ''
install_package git ''
install_package git ''
install_package git-cal ''
install_package git-cal ''
install_package glib ''
install_package glib ''
install_package gmp ''
install_package gmp ''
install_package gnuplot ''
install_package gnuplot '--with-cairo'
install_package go ''
install_package go ''
install_package gobject-introspection ''
install_package gobject-introspection ''
install_package gocart ''
install_package gocart ''
install_package graphicsmagick ''
install_package graphicsmagick ''
install_package groovy ''
install_package groovy ''
install_package harfbuzz ''
install_package harfbuzz ''
install_package htop-osx ''
install_package htop-osx ''
install_package httping ''
install_package httping ''
install_package httpry ''
install_package httpry ''
install_package hub ''
install_package hub ''
install_package hugo ''
install_package hugo ''
install_package icu4c ''
install_package icu4c ''
install_package imagemagick ''
install_package imagemagick ''
install_package irssi ''
install_package irssi ''
install_package jemalloc ''
install_package jemalloc ''
install_package jfrog-cli-go ''
install_package jfrog-cli-go ''
install_package jpeg ''
install_package jpeg ''
install_package jq ''
install_package jq ''
install_package libevent ''
install_package libevent ''
install_package libffi ''
install_package libffi ''
install_package libgpg-error ''
install_package libgpg-error ''
install_package libksba ''
install_package libksba ''
install_package libpng ''
install_package libpng ''
install_package libtermkey ''
install_package libtermkey ''
install_package libtiff ''
install_package libtiff ''
install_package libtool ''
install_package libtool ''
install_package libuv ''
install_package libuv ''
install_package libvterm ''
install_package libvterm ''
install_package libwebsockets ''
install_package libwebsockets ''
install_package libyaml ''
install_package libyaml ''
install_package lighttpd ''
install_package lighttpd ''
install_package little-cms ''
install_package little-cms ''
install_package little-cms2 ''
install_package little-cms2 ''
install_package lua ''
install_package lua ''
install_package lynx ''
install_package lynx ''
install_package maven ''
install_package maven ''
install_package mobile-shell ''
install_package mobile-shell ''
install_package mongodb ''
install_package mongodb ''
install_package msgpack ''
install_package msgpack ''
install_package mvn-bump ''
install_package mvn-bump ''
install_package neovim ''
install_package neovim ''
install_package nginx ''
install_package nginx ''
install_package nmap ''
install_package nmap ''
install_package oniguruma ''
install_package oniguruma ''
install_package openssl ''
install_package openssl ''
install_package openssl@1.1 ''
install_package openssl@1.1 ''
install_package pandoc ''
install_package pandoc ''
install_package pango ''
install_package pango ''
install_package pcre ''
install_package pcre ''
install_package perl ''
install_package perl ''
install_package phantomjs ''
install_package phantomjs ''
install_package phantomjs198 ''
install_package phantomjs198 ''
install_package phantomjs@1.98 ''
install_package phantomjs@1.98 ''
install_package pixman ''
install_package pixman ''
install_package pkg-config ''
install_package pkg-config ''
install_package protobuf ''
install_package protobuf ''
install_package python ''
install_package python ''
install_package python3 ''
install_package python3 ''
install_package ranger ''
install_package ranger ''
install_package rbenv ''
install_package rbenv ''
install_package readline ''
install_package readline ''
install_package reattach-to-user-namespace ''
install_package reattach-to-user-namespace ''
install_package redis ''
install_package redis ''
install_package rhino ''
install_package rhino ''
install_package ripgrep ''
install_package ripgrep ''
install_package ruby ''
install_package ruby ''
install_package ruby-build ''
install_package ruby-build ''
install_package scons ''
install_package scons ''
install_package sqlite ''
install_package sqlite ''
install_package ssh-copy-id ''
install_package ssh-copy-id ''
install_package stunnel ''
install_package stunnel ''
install_package subversion ''
install_package subversion ''
install_package swig ''
install_package swig ''
install_package the_silver_searcher ''
install_package the_silver_searcher ''
install_package thefuck ''
install_package thefuck ''
install_package tig ''
install_package tig ''
install_package tmux ''
install_package tmux ''
install_package tree ''
install_package tree ''
install_package ttyrec ''
install_package ttyrec ''
install_package unibilium ''
install_package unibilium ''
install_package vim ''
install_package vim '--with-python3 --without-python'
install_package w3m ''
install_package w3m ''
install_package watch ''
install_package watch ''
install_package webp ''
install_package webp ''
install_package wget ''
install_package wget ''
install_package xz ''
install_package xz ''
install_package z ''
install_package z ''
[ ! -z $failed_items ] && echo The following items were failed to install: && echo $failed_items
