#!/bin/bash

# initialize and update submodules
git submodule init
git submodule update
# cd .vim/bundle/vimproc.vim/ && make && cd -

# working directory
PWD=$(pwd)

# array of refs
REFS=(".common_profile" ".bashrc" ".profile" ".bash_profile" ".zshrc" ".zprofile" ".oh-my-zsh" ".vimrc" ".vim" ".gitconfig" ".bash-git-prompt" ".tmux.conf" ".tmuxinator.bash" ".tmuxinator" "git-completion.bash")

# loop through refs, move to backup if exists, create symlink
for i in "${REFS[@]}"
do
    if [ -f "$HOME/$i" ] || [ -d "$HOME/$i" ] && [ ! -h "$HOME/$i" ]; then
        mv -f "$HOME/$i" "$HOME/$i-bkup"
    fi
    if [ -d "$HOME/$i" ]; then
        ln -sf "$PWD/$i" "$HOME"
    else
        ln -sf "$PWD/$i" "$HOME/$i"
    fi
done

#ln -sf "$PWD/machellerogden.zsh-theme" "$PWD/.oh-my-zsh/themes/machellerogden.zsh-theme"
