#!/bin/bash

# initialize and update submodules
git submodule init
git submodule update

# working directory
PWD=$(pwd)
# array of refs
REFS=(".profile" ".vimrc" ".vim" ".gitconfig" ".bash-git-prompt" ".tmux.conf" ".tmuxinator.bash")

# loop through refs, move to backup if exists, create symlink
for i in "${REFS[@]}"
do
    if [ -f $HOME/$i ] || [ -d $HOME/$i ] && [ ! -h $HOME/$i ]; then
        mv -f $HOME/$i $HOME/$i-bkup
    fi
    ln -sf $PWD/$i $HOME/$i
done
